# Generated by Django 5.2.10 on 2026-02-05 02:57

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('booking_date', models.DateTimeField(default=datetime.datetime(2026, 2, 5, 2, 57, 40, 150593, tzinfo=datetime.timezone.utc))),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Ongoing'), (2, 'Finished'), (3, 'Canceled')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('duration_seconds', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeSeat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('price_modifier_cents', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Screening',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('base_price_cents', models.PositiveIntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.movie')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.room')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('row_letter', models.CharField(max_length=2)),
                ('column_number', models.PositiveSmallIntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='booking.room')),
                ('type_seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.typeseat')),
            ],
        ),
        migrations.CreateModel(
            name='ScreeningSeat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('seat_status', models.PositiveSmallIntegerField(choices=[(1, 'Available'), (2, 'Held'), (3, 'Sold')], default=1)),
                ('held_until', models.DateTimeField(blank=True, null=True)),
                ('screening', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screening_seats', to='booking.screening')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.seat')),
            ],
            options={
                'unique_together': {('screening', 'seat')},
            },
        ),
        migrations.CreateModel(
            name='BookingDetail',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price_paid_cents', models.PositiveIntegerField()),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_details', to='booking.booking')),
                ('screening_seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='booking.screeningseat')),
            ],
            options={
                'unique_together': {('booking', 'screening_seat')},
            },
        ),
    ]
