# Generated by Django 5.2.10 on 2026-02-08 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_booking_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='duration_seconds',
        ),
        migrations.AddField(
            model_name='movie',
            name='duration_minutes',
            field=models.PositiveSmallIntegerField(default=60),
            preserve_default=False,
        ),
    ]
